[build] 
    ignore = "if [ ${COMMIT_REF} == ${CACHED_COMMIT_REF} ] ; then false ; else git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ../event-app ../lib ; fi"

[build.environment]
PNPM_FLAGS = "--filter event-app..."